version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: TOK BOR

    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/app/data  # Ma'lumotlarni saqlash uchun jild
    restart: unless-stopped  # Konteyner o'chganda avto-qayta ishga tushadi

volumes:
  data:  # Ma'lumotlarni saqlash uchun nomlangan jild

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16  # Yangi subnet